Added option for anchor swap
edgarriba/examples pull request #2
Opened 2017-04-30 06:59 UTC by ducha-aiki

2017-04-30 23:05 UTC, edgarriba requested changes

2017-04-30 23:05 UTC, edgarriba commented on triplet/main.py
> +            loss += F.triplet_margin_loss(out_p, out_a, out_n, margin=args.margin)
you forgot adding the flag 
https://github.com/pytorch/pytorch/blob/master/torch/nn/functional.py#L681

no need for if statement just pass the argument
```
loss += F.triplet_margin_loss(out_p, out_a, out_n, margin=args.margin, swap=args.anchorswap) 
```

2017-04-30 23:09 UTC, edgarriba commented
@ducha-aiki please also update README

2017-05-01 07:52 UTC, ducha-aiki commented
@edgarriba Done.

2017-05-03 17:05 UTC, edgarriba approved these changes

2017-05-03 17:06 UTC, merged